name: ollama_api
description: A starting point for Dart libraries or applications.
version: 1.0.0

repository: https://github.com/adbonnin/dart_ollama_api
issue_tracker: https://github.com/adbonnin/dart_ollama_api/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http: ">=0.13.0 <2.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  nock: ^1.2.3
